name: Docker Image CI

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blackleg/asterisk --progress=plain
    - name: Test image
      run: docker run --rm blackleg/asterisk asterisk -V
    - name: Login to Docker Hub
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image
      if: ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
      run: |
        VERSION=$(git describe --always --tags)
        docker tag blackleg/asterisk blackleg/asterisk:$VERSION
        docker push blackleg/asterisk:$VERSION
        docker push blackleg/asterisk:latest
